<?php

echo $_SERVER['HTTP_USER_AGENT'], PHP_EOL;
echo $_SERVER['REMOTE_ADDR'], PHP_EOL;
echo $_SERVER['HTTP_HOST'], PHP_EOL;
echo $_SERVER['DOCUMENT_ROOT'], PHP_EOL;
echo $_SERVER['REQUEST_METHOD'], PHP_EOL;
echo $_SERVER['QUERY_STRING'], PHP_EOL;
echo $_SERVER['REQUEST_URI'], PHP_EOL;
